-- medical_equipment_products
INSERT INTO product (id, name, price, description, cid, permission) VALUES (1, 'Syringes, cannulas, and needles', 2205.2, 'all sizes and types including kits', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (2, 'Catheters', 5027.39, 'all sizes and types including kits', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (3, 'Coils, guidewire', 5417.7, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (4, 'Guidewires, all', 756.87, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (5, 'Medical tubing or hoses less than 2” diameter', 7009.84, 'including associated adaptors, connectors, caps, clamps, retainers, brackets, valves, washers, vents, stopcocks, or flow sensors and peristaltic pumps with flowrates of less than 600 liters/hr for such tubing (note: does not include tubing made of butyl rubber or greater than 35% fluoropolymers)', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (6, 'Endoscopic devices', 7781.85, 'including laryngoscopes, laparoscopes, anascopes, proctoscopes, arthroscopes, sinuscopes, dematoscopes, ophthalmoscopes, sigmoidscopes, otoscopes, retinoscopes, or colposcopes', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (7, 'Blood pressure monitors, gauges, cuffs, aneroids, or infusors', 7760.98, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (8, 'Monitor', 4150.69, 'for glucose management', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (9, 'Medical defibrillators', 5777.35, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (10, 'Medical lavage systems', 2865.5, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (11, 'IV sets, bags, and armboards', 420.9, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (12, 'Medical penlights', 1728.3, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (13, 'Stethoscopes', 554.56, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (14, 'Speculums', 5881.09, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (15, 'Medical scissors', 6994.86, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (16, 'Forceps', 2612.95, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (17, 'Single-use medical procedure trays and kits', 5991.25, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (18, 'Medical diagnostic kits, point-of-care', 5900.02, 'including EAR99 reagents', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (19, 'Reflex hammers', 7976.0, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (20, 'Blood lancets', 2544.24, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (21, 'Clinical swabs, applicators, specimen collectors, sponges, pads, tongue depressors, wooden spoons, cotton balls, or cotton rolls', 1131.53, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (22, 'Antiseptic wipes', 7509.73, 'for human use (including alcohol, antimicrobial, benzalkonium, betadine, iodine, and witch hazel)', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (23, 'Splints', 6985.49, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (24, 'Canes, crutches, walkers, rollators', 4491.16, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (25, 'Patient wheelchairs, chairs, gurneys, stretchers, mats, and cots', 4728.67, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (26, 'Patient transfer chairs, lifts, benches, boards, slides, discs, slings, and sheets', 5951.33, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (27, 'Safety poles, rails, handles, benches, grab bars, commode aids, and shower aids', 7045.59, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (28, 'Ear plugs and muffs', 1853.59, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (29, 'Otology sponges', 4677.21, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (30, 'Ear syringes', 4225.85, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (31, 'Ear wax removers', 3466.27, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (32, 'Patient vital-sign monitoring devices', 4660.04, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (33, 'Limb prosthesis devices', 7091.7, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (34, 'Orthopedic supports, braces, wraps, shoes, boots, or pads', 5307.92, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (35, 'Medical casts, padding', 3560.02, 'with  casting and removal equipment', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (36, 'Orthopedic traction devices and tables', 500.55, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (37, 'Human body positioners', 7058.57, 'including pads, wedges, cradles, pillows, rests, straps, supports, and holders', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (38, 'Human specimen collectors and containers', 6394.33, '(e.g., urine, blood, tissue)', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (39, 'Medical bandages, gauze, dressings, tape, swabs, sponges, and burn dressings', 3280.39, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (40, 'Surgical sutures and staples', 6007.34, 'with  removal kits', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (41, 'Tourniquets', 5203.9, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (42, 'Thermometers', 3539.16, 'for measuring human body temperature', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (43, 'Clinical basins, bowls, baths, pans, urinals, bags, and buckets', 5936.42, 'with  holding devices for such items', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (44, 'Medical carafes, cups, containers and tumblers', 941.82, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (45, 'Medicine cups', 3006.72, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (46, 'Syringe aspirators', 1847.86, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (47, 'Medical bags', 3687.29, 'for medical supplies and equipment including pre-packed bags', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (48, 'Condoms', 3342.49, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (49, 'Medical labels, labellers, stickers, forms, charts, signage, tags, cards, tape, wrist bands, documents, brochures, and graphics', 3245.46, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (50, 'Non-electronic patient medical record file systems and organizers', 2761.47, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (51, 'Beds', 2912.99, 'hospital beds, cribs, or bassinets including mattresses, overlays, pillows, and bumpers', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (52, 'Medical linens', 2283.52, '(e.g., blankets, sheets, pillow cases, towels, washcloths, drapes, covers)', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (53, 'Chairs', 3029.64, 'exam, treatment, surgical, dental, or phlebotomy', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (54, 'Stools', 574.42, 'designed for clinical use', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (55, 'Stands', 7865.08, 'IV, instrument, solution, or hamper', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (56, 'Carts', 1533.64, 'medical, medical utility, medical supply, food service, or hospital laundry carts', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (57, 'Tables', 5832.35, 'operating, exam, therapy, overbed, treatment, medical utility, or medical instrument', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (58, 'Jars and containers', 6230.58, 'designed for medical supplies and instruments less than 5 L internal volume', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (59, 'Privacy screens and curtains', 6570.2, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (60, 'Cabinets', 2850.87, 'medical supply or pharmaceutical', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (61, 'Floor mats', 1850.41, 'safety, anti-fatigue or special-purpose medical floor mats', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (62, 'Hydrocollator heating units', 6445.29, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (63, 'Warmers', 8075.62, 'bottle, gel, lotion, or blanket', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (64, 'Patient heating and cooling devices', 3697.7, 'pads, packs, bottles, bags, warmers, blankets, patches, lamps, bags', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (65, 'Paraffin baths', 5621.83, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (66, 'Lights and lamps', 3368.46, 'surgical, or medical exam, magnifying', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (67, 'Scales, stadiometers, rulers, sticks, tapes, protractors, volumeters, gauges, or calipers', 5227.31, 'designed for human measurement', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (68, 'Patient safety devices', 1754.85, 'including vests, aprons, finger mitts, limb or body holders, jackets, belts, restraints, cuffs, straps, or protectors', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (69, 'Human body or cadaver bags and shrouds', 4025.69, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (70, 'Adhesive', 4124.73, 'designed for human use', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (71, 'Adhesive remover', 4815.89, 'designed for human use', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (72, 'Telemetry pouches', 2546.84, 'designed for human use', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (73, 'Bottles (prescription)', 5397.6, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (74, 'Capnograph', 5834.02, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (75, 'CPAP (continuous positive airway pressure) systems and all components', 4842.33, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (76, 'Medical Flowmeters, oxygen & air', 2147.88, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (77, 'Humidifiers', 4117.54, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (78, 'Manikin, medical training, CPR', 3328.05, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (79, 'Medical Pumps', 2549.36, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (80, 'Ventilator, adult and tubing and accessories', 5143.02, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (81, 'Oxygen apparatus, all', 115.15, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (82, 'Pulse oximeter', 1794.1, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (83, 'Refrigerator, compartmental', 1197.57, 'for morgues', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (84, 'Spirometer', 4154.89, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (85, 'Tents, pediatric, aerosol, & mist', 3221.62, '', 1, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (86, 'Air bags and tidal volume bags', 6064.74, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (87, 'Air bellows', 5316.35, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (88, 'Anaesthesia circuits', 18399.61, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (89, 'Anaesthesia machines, vaporizers, nebulizers, and inhalers', 20009.84, 'designed for individual human use', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (90, 'Anaesthesia masks (', 21986.61, 'including laryngeal)', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (91, 'Anti-siphon equipment', 215.22, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (92, 'Block and epidural trays packaged', 12886.46, 'for individual use', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (93, 'Endotrach tubes', 15296.58, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (94, 'Head straps and harnesses', 21000.35, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (95, 'Hyperinflation systems', 803.38, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (96, 'In-line filters and cartridges, thermometers, CO2 detectors, sodalime canisters, and temperature and moisture exchangers', 21383.87, '(note: gas mask canisters, other than sodalime canisters designed for anaesthesia systems, require a specific license)', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (97, 'Intubation sets, probes and related equipment', 17419.12, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (98, 'Anaesthesiometers', 11487.86, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (99, 'Oral airways', 3325.56, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (100, 'Peripheral nerve stimulators', 17509.85, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (101, 'Anaesthesia pressure tubes and controllers', 10914.35, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (102, 'Cardiopulmonary resuscitation (CPR) training manikins and lung bags', 1449.98, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (103, 'Vibration dampening mounts', 3696.62, '', 2, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (104, 'Patient clothing', 33296.81, 'including gowns, slippers, underpads, or undergarments', 3, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (105, 'Surgical sleeve protectors', 8304.79, '', 3, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (106, 'Disposable latex, nitrile, polyethylene, vinyl gloves/finger cots or other medical gloves', 27562.82, '', 3, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (107, 'Medical gowns, scrubs, aprons, uniforms, lab coats, and coveralls', 35675.67, 'only those without integrated hoods', 3, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (108, 'Head or beard covers and nets', 25703.9, '', 3, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (109, 'Medical shoe and boot covers', 11697.52, '', 3, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (110, 'Ventilated Safety eyeshields and goggles', 13808.29, '(does not include full face shield or indirectly- vented goggles)', 3, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (111, 'Surgicalface or dust masks', 17128.47, '(does not include masks with respirators)', 3, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (112, 'Electrocardiography machines', 43461.95, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (113, 'Ablation devices and accessories, radio frequency', 16198.68, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (114, 'Balloon (extractor, retrieval)', 19511.96, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (115, 'Cardiac pacemaker', 23990.13, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (116, 'Cardiac programmer', 35444.72, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (117, 'Cardiac monitors, implantable or external', 33355.81, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (118, 'Cardiopulmonary oxygenation systems, devices, and monitors', 44822.86, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (119, 'Coagulation machines', 22939.45, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (120, 'Heart positioners, surgical revascularization', 43391.58, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (121, 'Heart valves , surgical, transcatheter (non-surgical)', 47636.57, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (122, 'Inflation devices, interventional', 526.29, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (123, 'Filters, arterial', 36000.98, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (124, 'Grafts, peripheral bypass', 30628.11, '', 4, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (125, 'Dental instruments', 51056.91, 'all types and sizes', 5, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (126, 'Dental instrument cases, trays, mats or tray liners, racks, covers, wraps, stands, holders, stringers, or protectors', 61803.07, '', 5, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (127, 'Bone graft matrix', 38774.74, '', 5, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (128, 'Dentures, crowns, molds, orthodontics, all', 24861.65, '', 5, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (129, 'Dental and oral implants or devices', 28162.28, '', 5, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (130, 'Tooth and denture brushes', 49951.06, '', 5, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (131, 'Denture and temporary oral device containers  Yankauers', 75934.91, '', 5, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (132, 'Bladder scanners', 13407.62, '', 6, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (133, 'Pouches, urostomy', 40362.57, '', 6, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (134, 'Bladder control pads, briefs, liners, underwear, pants and diapers', 78701.87, '', 6, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (135, 'Feminine hygiene products', 65755.98, '', 6, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (136, 'Fecal/stool management devices, kits, and catheters', 76670.68, '', 6, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (137, 'Enema sets', 68183.19, '', 6, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (138, 'Extracorporeal Lithotripter', 6264.43, '', 6, 5);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (139, 'Autoclaves', 14431.59, 'for medical instrument sterilization and accessories', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (140, 'Flow cytometry accessories, reagents and components', 69604.98, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (141, 'Laboratory balances and scales not to exceed 10 Kg', 71652.95, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (142, 'Patient blood gas analyzers', 54904.64, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (143, 'Medical specimen centrifuges', 82465.57, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (144, 'Automated clinical chemistry analyzers', 14844.23, 'for patient care', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (145, 'Coagulation analyzers', 11847.95, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (146, 'Co-oximeters', 82320.07, 'for haemoglobin analysis', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (147, 'Medical bone densitometers', 91259.6, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (148, 'Medical differential counters', 77638.07, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (149, 'Bench-top dry bath incubators', 85521.47, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (150, 'Electrolyte analyzers', 86164.2, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (151, 'Hematology analyzers', 36003.59, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (152, 'Histology and cytology strainers and tissue baths', 8341.58, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (153, 'Laboratory hot plates with less than 1.0 sq. ft. heating surface', 89238.87, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (154, 'Clinical immunoassay analyzers', 70506.83, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (155, 'Luminometers', 28923.54, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (156, 'Laboratory pH meter', 85098.84, '(with or without temperature probe)', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (157, 'Automated blood culture systems', 58076.23, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (158, 'Microplate readers/washers', 8812.45, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (159, 'Light microscopes  Osmometers', 15672.53, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (160, 'Pipettes', 111845.74, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (161, 'Medical refrigerators and freezers with less than 5.0 cu. ft. internal volume', 61327.24, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (162, 'Spectrophotometers, photometers, and colorimeters', 25286.23, 'designed for clinical use', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (163, 'Urinalysis analyzers', 45805.19, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (164, 'Clinical laboratory water baths less than 10 liter', 88186.5, '', 7, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (165, 'Hemodialysis machines', 104994.76, 'with  dialysis filters designed for such machines (Note: Other dialysis equipment, filters, and parts not used for hemodialysis require a specific license and may be controlled under 15 CFR, part. 774, supp. 1, ECCN 2B352.d)', 8, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (166, 'Hemodialysis connection or tubing kits', 133672.26, '', 8, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (167, 'Electroencephalography machines', 42961.72, '', 9, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (168, 'Neurostimulator, implantable', 184841.06, '', 9, 4);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (169, 'Umbilical cord clamps', 52639.91, '', 10, 3);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (170, 'Neonatal equipment (phototherapy, nasal CPAP, etc and all components)', 17549.17, '', 10, 3);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (171, 'Incubator /Isolette', 36262.5, '', 10, 3);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (172, 'Ventilator, infant/pediatric and tubing and accessories', 54389.03, '', 10, 3);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (173, 'Infant Radiant Warmer and parts and accessories', 209077.56, '', 10, 3);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (174, 'Contact Lenses, corrective', 87802.44, '', 11, 3);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (175, 'Contact Lens cleaning solutions', 125662.3, '', 11, 3);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (176, 'Glasses, corrective', 67640.68, '', 11, 3);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (177, 'Eyecharts  Phoropter  Tonometer', 18914.24, '', 11, 3);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (178, 'Hearing Aids, accessories and components', 188609.57, '', 12, 3);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (179, 'Bath cubes, therapy', 54975.81, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (180, 'Boots, mitts, and liners', 69376.15, 'for therapeutic pain relief', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (181, 'Orthopedic shoes, boots, etc', 119910.8, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (182, 'Parallel bars', 145705.3, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (183, 'Exercise bars', 289796.17, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (184, 'Hand bars', 150836.4, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (185, 'Mat Platforms', 14064.95, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (186, 'Exercise table', 217431.83, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (187, 'Medical Whirlpools', 81032.8, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (188, 'Mobility platforms, parallel bars, ladders, stairs', 190872.85, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (189, 'Balance pads, platforms, and beams', 204455.1, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (190, 'Cognitive measuring devices and equipment', 147150.89, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (191, 'Manipulation boards', 179004.75, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (192, 'Dining aids', 132194.03, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (193, 'Hydraulic dynamometer', 277043.64, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (194, 'Scoliometer', 262238.0, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (195, 'Goniometers', 300100.99, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (196, 'Pedometers', 163281.5, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (197, 'Ergometers', 254517.74, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (198, 'Rulonmeters', 128257.14, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (199, 'Fine motor assessment equipment', 104892.11, 'designed for human use', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (200, 'Tactile sensation, sensitization, and desensitization equipment', 52827.05, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (201, 'Rehabilitation exercise, weights, band, balls, boards, and mobility equipment', 250621.59, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (202, 'Therapeutic putty', 75926.07, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (203, 'Aquatic floats and training devices', 146599.37, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (204, 'Protective headgear', 289807.81, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (205, 'Electrotherapy, muscle stimulators, and tens units', 29716.48, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (206, 'Ultrasound stimulators', 68883.25, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (207, 'Massaging equipment', 152774.18, '', 13, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (208, 'Computed Tomography Scanners (CT, MDCT)', 34599.73, '', 14, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (209, 'Positron Emission Tomography (PET)', 336195.28, '', 14, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (210, 'Scintillation Camera/Anger camera', 304584.89, 'for medical imaging', 14, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (211, 'Magnetic Resonance Imaging (MRI) machines', 248584.75, '', 14, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (212, 'X-ray machines', 214770.23, '', 14, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (213, 'Parts and accessories', 41525.34, 'for medical imaging devices above that do not contain nuclear or chemical components.', 14, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (214, 'Medical ultrasound machines', 143102.01, '', 14, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (215, 'Medical/dental film', 234361.31, '', 14, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (216, 'Aseptic, germicidal, or disinfectant wipes or clothes', 195113.28, 'for medical equipment, devices or furniture', 15, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (217, 'Ready-to-use disinfectant in 32 oz. containers or less', 223580.76, '', 15, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (218, 'Aseptic, germicidal, or medical-grade soap, detergent, pre-soak, or rinse in 1 gallon containers or less', 280250.5, '', 15, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (219, 'Hand sanitizer, lotion, soap, scrub, wash, gel, or foam', 208989.27, 'including dispensing devices', 15, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (220, 'Medical cleaning brushes', 88117.42, 'for equipment, patients, and furniture', 15, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (221, 'Sterilization or disinfection indicator strips, tape, or test packs', 154644.54, '', 15, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (222, 'Medical instrument sterilization pouches, mats, protector guards, or tubing', 254147.38, '', 15, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (223, 'Sterilization containers or cases less than 0.3 cu. ft.', 208677.59, '', 15, 2);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (224, 'Cervical fusion kit', 11963.8, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (225, 'Image- guiding surgery products, ear, nose and throat', 323789.41, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (226, 'Orthopedic plates/screws, fixators, implants, cement', 437452.92, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (227, 'Surgical shunts', 21695.4, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (228, 'Tissue Stabilizer, surgical revascularization', 84252.9, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (229, 'Surgical clips', 148726.83, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (230, 'Surgical instruments', 93900.41, 'all types and sizes', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (231, 'Surgical instrument cases, trays, mats or tray liners, racks, covers, wraps, stands, holders, stringers, or protectors', 268791.28, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (232, 'Stents', 385144.85, 'all types and sizes', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (233, 'Surgical linens, drapes, or covers', 430491.33, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (234, 'Chest drains', 307262.12, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (235, 'Surgical case carts', 168482.74, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (236, 'Blood transfusion equipment', 364565.86, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (237, 'Surgical clean-up kits', 431275.45, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (238, 'Wound drainage equipment', 291048.27, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (239, 'Stockinettes', 375362.08, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (240, 'Surgical mesh', 399793.59, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (241, 'Surgical smoke evacuators and specialized supporting equipment', 103663.74, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (242, 'Electrosurgery devices and supporting equipment', 129793.91, '', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (243, 'Autoclaves with chamber sizes less than 0.3 cu. ft.', 196676.16, 'including trays, containers, cassettes, cases, and filters for such systems.', 16, 1);
INSERT INTO product (id, name, price, description, cid, permission) VALUES (244, 'Lubricant specially-formulated', 151269.02, 'for surgical equipment in 1 gallon containers or less', 16, 1);
